Messages:
  disenchanted: '&5Enchanty smazány.'
  needs-to-be-enchanted: '&cNástroj musí byt enchantován.'
  need-to-hold-an-item: '&cMusís v ruce drzet nejáky nástroj.'
  players-only: '&cTento príkaz je jen pro hráce.'
  reloaded: '&5Reloaded.'
  no-perms: '&cNa tohle nemás pravomoce.'
Effects:
  sound: true
  particle: true